local ScreenGui = Instance.new("ScreenGui")
local TextLabel = Instance.new("TextLabel")
ScreenGui.Parent = game.CoreGui
TextLabel.Parent = ScreenGui
TextLabel.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
TextLabel.Position = UDim2.new(0.20201239, 0, 0.250927061, 0)
TextLabel.Size = UDim2.new(0, 259, 0, 50)
TextLabel.Font = Enum.Font.SourceSans
TextLabel.Text = "This script has been removed due to being patched (new anti-wipe)"
TextLabel.TextColor3 = Color3.fromRGB(0, 0, 0)
TextLabel.TextSize = 15.000
